name: Job Scraper

# We'll run our scraper every hour.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ----- Caching -------------------------------------------------------------------

      # Caches our dependencies to stop our action from taking too long to complete.
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-v2-${{ hashFiles('**/requirements.txt') }}

      # Caches our browsers so our actions run faster.
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}

      # Caches the HuggingFace model so it's only downloaded on the first run.
      - name: Cache HuggingFace model
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: hf-minilm-l6-v2

      - name: Install dependencies
        run: |
          pip install playwright python-dotenv resend sentence-transformers torch transformers jobspy
          playwright install-deps chromium
          playwright install chromium

      # ----- Scripting ------------------------------------------------------------------

      - name: Run scraper
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          JOBRIGHT_EMAIL: ${{ secrets.JOBRIGHT_EMAIL }}
          JOBRIGHT_PASSWORD: ${{ secrets.JOBRIGHT_PASSWORD }}
          APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }}
          CUDA_VISIBLE_DEVICES: ""
        run: python3 bin/scraper.py
