name: Job Scraper

# We'll run our scraper 4 times a day in 6 hour intervals.
on:
  schedule:
    - cron: '0 10 * * *'  
    - cron: '0 16 * * *'   
    - cron: '0 22 * * *'  
    - cron: '0 4 * * *'  
  workflow_dispatch:      

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: Albert 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright python-dotenv
          playwright install chromium

      - name: Run scraper
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.NOTIFIER_EMAIL_PASSWORD }}
        run: python3 bin/scraper.py
